name = "Damask"
uuid = "df89811a-4d26-430f-8d7e-ef7a2e79a656"
authors = ["The DAMASK team <damask@mpie.de>"]
version = "0.0.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
